config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :asistancees
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asistancee.rb
class Asistancee < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/asistancees_controller.rb
class AsistanceesController < ApplicationController
  before_action :set_asistancee, only: [:show, :edit, :update, :destroy]

  # GET /asistancees
  # GET /asistancees.json
  def index
    @asistancees = Asistancee.all
  end

  # GET /asistancees/1
  # GET /asistancees/1.json
  def show
  end

  # GET /asistancees/new
  def new
    @asistancee = Asistancee.new
  end

  # GET /asistancees/1/edit
  def edit
  end

  # POST /asistancees
  # POST /asistancees.json
  def create
    @asistancee = Asistancee.new(asistancee_params)

    respond_to do |format|
      if @asistancee.save
        format.html { redirect_to @asistancee, notice: 'Asistancee was successfully created.' }
        format.json { render :show, status: :created, location: @asistancee }
      else
        format.html { render :new }
        format.json { render json: @asistancee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asistancees/1
  # PATCH/PUT /asistancees/1.json
  def update
    respond_to do |format|
      if @asistancee.update(asistancee_params)
        format.html { redirect_to @asistancee, notice: 'Asistancee was successfully updated.' }
        format.json { render :show, status: :ok, location: @asistancee }
      else
        format.html { render :edit }
        format.json { render json: @asistancee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asistancees/1
  # DELETE /asistancees/1.json
  def destroy
    @asistancee.destroy
    respond_to do |format|
      format.html { redirect_to asistancees_url, notice: 'Asistancee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asistancee
      @asistancee = Asistancee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asistancee_params
      params.require(:asistancee).permit(:date_admisision, :student_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :dni)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asistancees_helper.rb
module AsistanceesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/asistancees/_form.html.erb
<%= form_for(asistancee) do |f| %>
  <% if asistancee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asistancee.errors.count, "error") %> prohibited this asistancee from being saved:</h2>

      <ul>
      <% asistancee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_admisision %>
    <%= f.datetime_select :date_admisision %>
  </div>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.text_field :student_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asistancees/edit.html.erb
<h1>Editing Asistancee</h1>

<%= render 'form', asistancee: @asistancee %>

<%= link_to 'Show', @asistancee %> |
<%= link_to 'Back', asistancees_path %>

app/views/asistancees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asistancees</h1>

<table>
  <thead>
    <tr>
      <th>Date admisision</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asistancees.each do |asistancee| %>
      <tr>
        <td><%= asistancee.date_admisision %></td>
        <td><%= asistancee.student %></td>
        <td><%= link_to 'Show', asistancee %></td>
        <td><%= link_to 'Edit', edit_asistancee_path(asistancee) %></td>
        <td><%= link_to 'Destroy', asistancee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asistancee', new_asistancee_path %>

app/views/asistancees/new.html.erb
<h1>New Asistancee</h1>

<%= render 'form', asistancee: @asistancee %>

<%= link_to 'Back', asistancees_path %>

app/views/asistancees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date admisision:</strong>
  <%= @asistancee.date_admisision %>
</p>

<p>
  <strong>Student:</strong>
  <%= @asistancee.student %>
</p>

<%= link_to 'Edit', edit_asistancee_path(@asistancee) %> |
<%= link_to 'Back', asistancees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QrcodewebcamAsisstance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :dni %>
    <%= f.text_field :dni %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Dni</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.dni %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @student.dni %>
</p>

<p>
  <strong>QR Code:</strong>
  <div id="qrcode-student" data-student="<%= @student.id%>">
    
  </div>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>